version: '3'

services:
  web:
    build: ./
    environment:
      - ALLOW_OVERRIDE=true
    volumes:
      - ./app:/var/www/html/
      - ./config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - my-network
    links:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb  # Nombre fijo para el contenedor MariaDB
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin  # Nombre fijo para el contenedor phpMyAdmin
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"  # HTTPS
      - "81:80"    # HTTP, redirigido a HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert.crt:/etc/nginx/certs/cert.crt
      - ./nginx/cert.key:/etc/nginx/certs/cert.key
      
      
    depends_on:
      - web
      - phpmyadmin
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
    driver: bridge

